### ISSUE TITLE
Gitのリモートにあげることができるようにする

### ISSUE THREAD

**Issue by fuchi0741** [masayatoida/MoneyCalculation#1]
git add 
git commit 
git push 
git status

これらのコマンドについて説明できるようにする

**Comment by masayatoida** [comment]
git add
git addは追加されたファイルなどをバージョン管理の対象として追加するためのコマンド。

git commit
簡単にファイルの進捗を管理するためにファイルの変更や追加などを保存しておく必要があり,そのためのコマンドがgit commit。git commitを利用すればファイルの変更をgitレポジトリに保存することができる。

git push
ローカルリポジトリの内容をリモートリポジトリに反映すること。

git status
作業ディレクトリ内のブランチをstatusコマンドで現在の状態を表示することができる。

git fetch
git fetchとはリモートリポジトリから最新情報をローカルリポジトリに持ってくるコマンド。

git merge
git mergeとは、各ブランチで編集した作業を反映させるためのコマンド。

**Comment by fuchi0741** [comment]
@masayatoida 
いい感じですね💡
ローカルにあるリポジトリをリモートにあげることはできそうですか？？
(SSHキーというやつを結局作って設定しなきゃかもです)

**Comment by masayatoida** [comment]
調べて見たのですが、ちょっとよくわからないです・・・
ターミナルで操作するのでしょうか？

**Comment by fuchi0741** [comment]
@masayatoida SSHキーは既に作成をしたため、
あとはターミナルで作成したSSHキーを作成
→ 確認したSSHキーをコピペして、Githubに設定
をする必要があります！

**Comment by fuchi0741** [comment]
@masayatoida 
> git add
> git commit
> git push
> git status
> 
> これらのコマンドについて説明できるようにする

こちらOKそうでしたら、このチケットをcloseしていただきたいです！

**Comment by fuchi0741** [comment]
右下の`Close Issue`ってボタンがあるので押せばOKです！

このチケット(今回だと、Gitのリモートにあげることができるようにする)が完了した意思表示になります！

この方法が仕事でよくあるので知っておくと良きです！

**Comment by masayatoida** [comment]
@fuchi0741 
了解です！ありがとうございます！

**Comment by masayatoida** [comment]
@fuchi0741 
このチケットを終了させていただきます。
