### ISSUE TITLE
ブランチを切れるようにする

### ISSUE THREAD

**Issue by fuchi0741** [masayatoida/MoneyCalculation#3]
## 先に #2 をやってください

git branch
git checkout 

ブランチの切り方とブランチの概念について説明できるようにすること

**Comment by masayatoida** [comment]
Gitでは、プロジェクトの変更履歴はただの一本線というわけでなく、分岐をさせて、枝分かれさせることができます。
その変更履歴の枝を「ブランチ」（branch）といいます。
例えば、複数人が同時に開発や執筆をする場合、同じ変更履歴を気ままに更新していったらわけがわからなくなります。
そうならないように、それぞれ別のブランチで作業を進めて、コミットを重ねていきます。
あるブランチが一定の作業を終えて、問題ないことが確認できたら、本流のブランチにそれを統合します。

最初はmainしか存在しないので執筆用のbranchを作成する必要がある。
→git branch branch名
→git branchコマンドで確認する


git checkout
実際の執筆作業の履歴はmainではなく、新たに作成したブランチに記録をしていきたいので、作業するブランチを切り替える必要がある。そのためには、git checkoutコマンドを用いる。
→git checkout branch名
→git checkoutコマンドで確認する

**Comment by masayatoida** [comment]
@fuchi0741 
 #6でブランチを切るのでこちらのチケットは閉じます、
