### ISSUE TITLE
Git-flowについて学習

### ISSUE THREAD

**Issue by fuchi0741** [masayatoida/MoneyCalculation#5]

**Comment by fuchi0741** [comment]
https://qiita.com/KosukeSone/items/514dd24828b485c69a05
について理解できるようにする

**Comment by masayatoida** [comment]
5回程度読み直し、ターミナルで実際に操作してみました。
記事が古いせいかエラーがでました。

**Comment by masayatoida** [comment]
Last login: Fri Mar 26 06:42:40 on ttys000
rie@toidarikounoMacBook-Pro MoneyCalculation % git clone https://github.com/masayatoida/MoneyCalculation.git

fatal: destination path 'MoneyCalculation' already exists and is not an empty directory.
rie@toidarikounoMacBook-Pro MoneyCalculation %

**Comment by fuchi0741** [comment]
@masayatoida エラー文が出ているため読んでみましょう💡

fatal: destination path 'MoneyCalculation' already exists and is not an empty directory.
既にMoneyCalculationという名前のディレクトリ(フォルダと同義)があり、名前が重複してしますためcloneできませんと怒られていそうです！
なので、cloneするために被っているフォルダを削除後にcloneコマンドを実施すると同じエラー文は出ないかと思います！

**Comment by masayatoida** [comment]
Last login: Fri Mar 26 06:44:45 on ttys000
rie@toidarikounoMacBook-Pro MoneyCalculation % git clone https://github.com/masayatoida/MoneyCalculation.git
fatal: destination path 'MoneyCalculation' already exists and is not an empty directory.
rie@toidarikounoMacBook-Pro MoneyCalculation % git clone https://github.com/masayatoida/MoneyCalculation.git
Cloning into 'MoneyCalculation'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 31 (delta 2), reused 31 (delta 2), pack-reused 0
Unpacking objects: 100% (31/31), done.

削除したらできました！ありがとうございます！！




rie@toidarikounoMacBook-Pro MoneyCalculation % git flow init
git: 'flow' is not a git command. See 'git --help'.

The most similar commands are
	reflog
	show

記事の通り次に進んだら上記の表示がでました。flowはgitのコマンドではなく、近いものはreflogかshowというコマンドと言われているみたいですが、どうしたらよいでしょうか？

**Comment by fuchi0741** [comment]
@masayatoida 
エラー解決できたようでよかったです！
その経験が増えるほど、実力がついてくると思います！

すいません！自分言っていなかったのですが、gitflowは概念さえ理解していただければ大丈夫です！
特に、インストール等をする必要はありません！🙏
そのため、今回でたエラーは無視して大丈夫です！

ps返信に気が付けずすいません😓
次からは @fuchi0741 のメンションをつけるかLINEにリマインドするかお願いします！

**Comment by fuchi0741** [comment]
概念については、
masterブランチ(またはmainブランチ)
developブランチ
featureブランチ
が、一旦理解できればOKです！

releaseブランチや
hotfixブランチは若干応用なので一旦スルーでOKです！

**Comment by masayatoida** [comment]
@fuchi0741 
では、こちらも閉じさせていただきます。
