### ISSUE TITLE
SSHキーを設計できるようにする

### ISSUE THREAD

**Issue by fuchi0741** [masayatoida/MoneyCalculation#7]
@masayatoida アサインしました！よろしくお願いします！

**Comment by fuchi0741** [comment]
@masayatoida SSHキーについての話題はこちらからお願いします！
(話の流れが追いやすくなるの恩恵があります！)

**Comment by masayatoida** [comment]
SSHキーの部分がよくわからないので、詳細に説明していただけないでしょうか？
https://backlog.com/ja/git-tutorial/reference/ssh/
このページに記載されていることを実施するのでしょうか？

**Comment by fuchi0741** [comment]
@masayatoida 
> 実施するのでしょうか？

実施してみて、その結果を共有して頂いた方が良いと思うので、次からそうしていただけると嬉しいです！
記事を参考にするとできそうです💡

SSHキーMacの部分を確認してみましたが、

ターミナルを表示
`ssh-keygen` コマンドを実行
`cat ~/.ssh/id_rsa.pub` コマンドを実行して、確認すして出力例のようなSSHKeyが出るかどうか確認をする

出力例(リンクよりコピペ)
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDkkJvxyDVh9a+zH1f7ZQq/JEI79dVjDSG
4RzttQwfK+sgWEr0aAgfnxdxQeDKxIxqI1SwyTY8oCcWzvpORuPqwbc7UWWPcCvbQ3jlEdN
5jvwKM82hincEWwI3wzcnVg2Mn8dH86b5m6REDzwRgozQ3lqrgwGVlTvkHDFs6H0b/1PSrM
XGppOP/QXGEVhZ6Hy4m3b1wMjjrbYwmWIeYklgoGHyrldhAaDYc33y7aUcRyFyq5DubtsLn
2oj4K+1q36iviCHxCOri0FDmn2dzylRCI4S+A2/P7Y7rVfdT+8OWYKCBUs8lfjujghEtejq
Qmj9ikyGTEAW1zQCN7hVwYdjL hoge@hoge.local
```

もし確認ができればgithubのSettingからSSHキーを設定する箇所があるので設定をする

**Comment by fuchi0741** [comment]
@masayatoida 
試してみて、どこまでうまくいったか教えてほしいですー！

**Comment by masayatoida** [comment]
@fuchi0741 


下記がターミナル操作のコピペです。

Last login: Mon Apr  5 20:27:27 on ttys000
rie@toidarikounoMacBook-Pro MoneyCalculation % ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/Users/rie/.ssh/id_rsa): cat ~/.ssh/id_rsa.pub
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Saving key "cat ~/.ssh/id_rsa.pub" failed: No such file or directory
rie@toidarikounoMacBook-Pro MoneyCalculation % 


ターミナルで教えていただいたコマンドを入力後、パスワードを求められたので入力しました。
Saving key "cat ~/.ssh/id_rsa.pub" failed: No such file or directory
そのようなファイルはないというエラーでしょうか？

**Comment by fuchi0741** [comment]
`Enter file in which to save the key (/Users/rie/.ssh/id_rsa): cat ~/.ssh/id_rsa.pub`
ここって
`Enter file in which to save the key (/Users/rie/.ssh/id_rsa): `
このタイミングでEnterは押しているのは正しいですか？？」

**Comment by masayatoida** [comment]
Last login: Sat Apr 10 08:16:37 on ttys000
rie@toidarikounoMacBook-Pro MoneyCalculation % ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/Users/rie/.ssh/id_rsa): 
/Users/rie/.ssh/id_rsa already exists.
Overwrite (y/n)? y
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /Users/rie/.ssh/id_rsa.
Your public key has been saved in /Users/rie/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:tBdXTkFzTaAQ0lg8bZrpac4l2vdM2arRmw2XHchCQI4 rie@toidarikounoMacBook-Pro.local
The key's randomart image is:
+---[RSA 3072]----+
|        oB+o .B++|
|        +.=.o= o.|
|       E...Bo .  |
|       . .=o. .  |
|        S..o o . |
|         .= o. o+|
|         * o. =.+|
|        . + .+ B |
|           ..o* .|
+----[SHA256]-----+
rie@toidarikounoMacBook-Pro MoneyCalculation % cat ~/.ssh/id_rsa.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCv5//hL3Fwj4QYlwBmS1WyOx2EG0D6lqkYDRyo5YsrKxg/gOwknCM/w1rFseLEbMqDXX9Agx1Xr7eadfrdUsmGFgSjHdYOGnSXJcVr5rQ+unNBSn1zYQt1SFHsn9kyfMplGmF/dBTYsAJwUmxizUEer33cy3YUvTSJ2Z16Z2AFBYpkkr/rbwKezlXhwLqeKAGJYOgw7MMYfl2glDcciv/SP2JDiJmSsgV2Ik6lA8TKnqVEkaKh1UQEzfCCeEg+JmkvHNdKhYfFCQZLB1fYbDD+oXotsZkVeJzDNrkEpfGHSf69uACFfd7ZTj03LT/VayfQDSXew+Vx0fyt8NAJ/noHGyN639VCl6AMyM20ySDgygTjlLwOc7+ve7hEWkg2wUePVatUyMTEKRtXWhfMmqLjzi6zJDwr7n1/rT4lcWIIqWcNFK0I80K9iK/UIQdOJ+2IYzevfxowuyxvi9EuQ5GNXzUJ03g0DT+Y8WNec46fo0V1eRI/KIL/1AGx2a2Oia8= rie@toidarikounoMacBook-Pro.local
rie@toidarikounoMacBook-Pro MoneyCalculation % 


出力できました!
githubにも設定してみました。

**Comment by masayatoida** [comment]
@fuchi0741 
Last login: Sat Apr 10 08:16:37 on ttys000
rie@toidarikounoMacBook-Pro MoneyCalculation % ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/Users/rie/.ssh/id_rsa):
/Users/rie/.ssh/id_rsa already exists.
Overwrite (y/n)? y
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /Users/rie/.ssh/id_rsa.
Your public key has been saved in /Users/rie/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:tBdXTkFzTaAQ0lg8bZrpac4l2vdM2arRmw2XHchCQI4 rie@toidarikounoMacBook-Pro.local
The key's randomart image is:
+---[RSA 3072]----+
| oB+o .B++|
| +.=.o= o.|
| E...Bo . |
| . .=o. . |
| S..o o . |
| .= o. o+|
| * o. =.+|
| . + .+ B |
| ..o* .|
+----[SHA256]-----+
rie@toidarikounoMacBook-Pro MoneyCalculation % cat ~/.ssh/id_rsa.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCv5//hL3Fwj4QYlwBmS1WyOx2EG0D6lqkYDRyo5YsrKxg/gOwknCM/w1rFseLEbMqDXX9Agx1Xr7eadfrdUsmGFgSjHdYOGnSXJcVr5rQ+unNBSn1zYQt1SFHsn9kyfMplGmF/dBTYsAJwUmxizUEer33cy3YUvTSJ2Z16Z2AFBYpkkr/rbwKezlXhwLqeKAGJYOgw7MMYfl2glDcciv/SP2JDiJmSsgV2Ik6lA8TKnqVEkaKh1UQEzfCCeEg+JmkvHNdKhYfFCQZLB1fYbDD+oXotsZkVeJzDNrkEpfGHSf69uACFfd7ZTj03LT/VayfQDSXew+Vx0fyt8NAJ/noHGyN639VCl6AMyM20ySDgygTjlLwOc7+ve7hEWkg2wUePVatUyMTEKRtXWhfMmqLjzi6zJDwr7n1/rT4lcWIIqWcNFK0I80K9iK/UIQdOJ+2IYzevfxowuyxvi9EuQ5GNXzUJ03g0DT+Y8WNec46fo0V1eRI/KIL/1AGx2a2Oia8= rie@toidarikounoMacBook-Pro.local
rie@toidarikounoMacBook-Pro MoneyCalculation %

出力できました!
githubにも設定してみました。

**Comment by fuchi0741** [comment]
@masayatoida 
おおおおおおお！すごいです！
自力でされたのがめちゃいいです！

Githubに設定ができたのであれば、このチケットはクローズしちゃってOKです！

**Comment by masayatoida** [comment]
@fuchi0741 
このチケットを閉じますね。
